### PR TITLE
WIP: impl for double short margin

### PR DESCRIPTION
**Pull request by kjr217**

### CODE REVIEW

**Comment by antoncoding** [comment]
Just for the record, putting the conversation from Discord here: 
One thing worth noticing with this version is that there's a big gap between the 2 scenarios 
1. both put and call are ITM (min requirement = min call requirement + min put requirement)
2. only one of the put and call is ITM. (min requirement = max (min call requirement + min put requirement))

**Comment by kjr217** [comment]
I think to solve this we either need some sort of smoothing function between the 2 scenarios, so either if it comes in range we dont default to mincall + minput or we dont defauly to just mincall or minput when only one side is in

**Comment by antoncoding** [comment]
Stepping one step back, this "gap" also already exists before this PR when you choose the 2 strikes:
if you do:
1. short 1500 call = minCollatCall
2. short 1500 call + short 1499 put: min collat = max(minCollatCall, minCollatPut) 
3. short 1500 call + short 1501 put: min collat = minCollatCall + minCollatPut
 
So if we looked at the strikes you're creating vs the collateral putting in, this is also not smoothed.

P.S. **(2) seems wrong**:  cuz you are creating 2 options with approximately collateral worth only a bit higher than one of them. My intuition is that we need to increase the initial collateral requirement when the 2 strikes are very close but not overlaps, too.

So maybe the starting point of only 1 option is ITM should also not be max(minCollatPut, minCollatCall)

**Comment by kjr217** [comment]
I see what youre getting at, i think in the example you give the step is a bit more subtle as its about the difference between put and call collateral requirements as opposed to single collateral requirements vs both collateral requirements. That being said, if we assume put-call parity then the put call collat shouldnt be different when they swap from one to the other.

**Pull request closed without merging**
